version: '3.8'

services:
  aptutil:
    image: ghcr.io/vanilla-os/aptutil:main
    restart: unless-stopped

    ports:
      - "3142:3142"

    volumes:
      - /vos-apt-data/lib:/var/lib/aptutil
      - /vos-apt-data/mirror:/var/spool/go-apt-mirror
      - /vos-apt-data/cache:/var/spool/go-apt-cacher
